In [1]:
import choclo
import harmonica as hm
import numba
import numpy as np
import verde as vd

import magali as mg

In [2]:
dipole_coordinates = (500, 500, -15)
true_inclination = 30
true_declination = 40
true_intensity = 5e-11

In [3]:
coordinates = vd.grid_coordinates(
    region=[-100, 100, -100, 100],
    spacing=2,
    extra_coords=5,
)

true_moment = hm.magnetic_angles_to_vec(
    inclination=true_inclination,
    declination=true_declination,
    intensity=true_intensity,
)

data = mg.dipole_bz(coordinates, dipole_coordinates, true_moment)

print(dipole_coordinates)
print(true_moment)

linear_model = mg.MagneticMomentBz((499, 499, -14))
linear_model.fit(coordinates, data)
print(linear_model.dipole_moment_)

(500, 500, -15)
(np.float64(2.783351996132097e-11), np.float64(3.3170697408446925e-11), np.float64(-2.4999999999999998e-11))
[ 3.02179525e-11  3.57779743e-11 -2.49737722e-11]


In [ ]:
# Initial guess
location = np.array([498, 498, -13])
moment = linear_model.dipole_moment_
print(location)
print(moment)

[495 495 -10]
[ 3.02179525e-11  3.57779743e-11 -2.49737722e-11]


In [7]:
nonlinear_model = mg.NonlinearMagneticDipoleBz(location, moment)
nl_location_, nl_moment_ = nonlinear_model.fit(coordinates, data)

In [6]:
print(dipole_coordinates)
print(true_moment)
print(nl_location_)
print(nl_moment_)

(500, 500, -15)
(np.float64(2.783351996132097e-11), np.float64(3.3170697408446925e-11), np.float64(-2.4999999999999998e-11))
[499.52699953 499.30003455  -8.27199836]
[ 4.35879814e-11  5.18907520e-11 -2.50243391e-11]
