In [1]:
import choclo
import harmonica as hm
import numba
import numpy as np
import verde as vd

import magali as mg

In [2]:
dipole_coordinates = (0, 0, -5)
true_inclination = 0
true_declination = 0
true_intensity = 1e-15

In [7]:
coordinates = vd.grid_coordinates(
    region=[-100, 100, -100, 100],
    spacing=2,
    extra_coords=5,
)

true_moment = hm.magnetic_angles_to_vec(
    inclination=true_inclination,
    declination=true_declination,
    intensity=true_intensity,
)

data = mg.dipole_bz(coordinates, dipole_coordinates, true_moment)

# print(dipole_coordinates)
# print(true_moment)
location_linear_model = (-0.062, 0.01937, -2.9997)
linear_model = mg.MagneticMomentBz(location_linear_model)
linear_model.fit(coordinates, data)
# print(linear_model.dipole_moment_)

print(location_linear_model)
print(linear_model.dipole_moment_)

(0, 0, -5)
(np.float64(0.0), np.float64(1e-15), np.float64(-0.0))
[1.15689137e-20 6.24218915e-16 1.34349536e-18]


In [4]:
# Initial guess
location = np.array([498, 498, -13])
moment = linear_model.dipole_moment_
print(location)
print(moment)

[498 498 -13]
[-9.59783834e-11  1.61773837e-11  4.64269691e-12]


In [5]:
nonlinear_model = mg.NonlinearMagneticDipoleBz(location, moment)
nl_location_, nl_moment_ = nonlinear_model.fit(coordinates, data)

In [6]:
print(dipole_coordinates)
print(true_moment)
print(nl_location_)
print(nl_moment_)

(0, 0, -5)
(np.float64(0.0), np.float64(1e-15), np.float64(-0.0))
[2717.9354005  4652.2965652  -169.12194599]
[-2.95355432e-07 -1.64731800e-07  2.83173155e-08]
